language: node_js
node_js:
  - 'stable'
install:
  - npm install
script:
  - npm run package:chromium
  - npm run package:firefox
deploy:
  provider: releases
  # ⋮
  api_key: ${github_api_key}
  draft: true
  file:
    - 'dist/xbrowsersync_${XBS_VERSION}_chromium.zip'
    - 'dist/xbrowsersync_${XBS_VERSION}_firefox.zip'
  on:
    all_branches: true
    tags: true
  skip_cleanup: true
