language: node_js
node_js:
  - 'stable'
install:
  - npm install
script:
  - npm run package:chromium
  - npm run package:firefox
  - 'echo ${XBS_VERSION} > version.txt'
before_deploy:
  - 'echo ready?'
  - export XBS_VERSION=$(cat version.txt)
  - 'echo ${XBS_VERSION}'
  - 'git tag v1.6.0.688'
deploy:
  provider: releases
  # ⋮
  file:
    - 'dist/xbrowsersync_${XBS_VERSION}_chromium.zip'
    - 'dist/xbrowsersync_${XBS_VERSION}_firefox.zip'
  on:
    all_branches: true
  prerelease: true
  token: ${github_api_key}
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/
