language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run package:chromium
  - npm run package:firefox
before_deploy:
  - export XBS_VERSION=$(cat version.txt)
  - git tag v${XBS_VERSION}
deploy:
  provider: releases
  # ⋮
  file:
    - dist/xbrowsersync_${XBS_VERSION}_chromium.zip
    - dist/xbrowsersync_${XBS_VERSION}_firefox.zip
  on:
    all_branches: true
  prerelease: true
  skip_cleanup: true
  token: ${github_api_key}
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+$/
