language: node_js
node_js:
  - 'stable'
install:
  - npm install
script:
  - npm run package:chromium
  - npm run package:firefox
deploy:
  provider: releases
  # ⋮
  api_key: ${github_api_key}
  draft: true
  file:
    - 'dist/xbrowsersync_1.6.0.0_chromium.zip'
    - 'dist/xbrowsersync_1.6.0.0_firefox.zip'
  on:
    all_branches: true
    tags: true
  skip_cleanup: true
