name: CI
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  build:
    name: Build platforms
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - uses: android-actions/setup-android@v2
      - name: Install Cordova
        run: npm install -g cordova@9.0.0
      - name: Install dependencies
        run: npm install
      - name: Prepare Cordova
        run: |
          pushd res/android
          cordova telemetry off
          cordova prepare
          popd
      - name: Build platform:chromium
        run: npm run build:chromium
      - name: Build platform:firefox
        run: npm run build:firefox
      - name: Build platform:android
        run: |
          npm run build:android
          cd build/android
          cordova build android
