name: CI
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
jobs:
  build_android:
    name: Build platform:android
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      ANDROID_SDK_ROOT:
      JAVA_HOME:
      PATH:
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - run: sdkmanager --list
