name: Release
on:
  workflow_dispatch:
    inputs:
      beta_release:
        required: true
        default: 'false'
jobs:
  package:
    name: Package platforms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - uses: android-actions/setup-android@v2
      - name:
        run: |
          cd $ANDROID_SDK_ROOT/build-tools
          ls -l
          echo "${{ env.ANDROID_SDK_ROOT }}/build-tools" >> $GITHUB_PATH
      - name: Install cordova
        run: |
          npm install -g cordova@9.0.0
          pushd res/android
          cordova telemetry off
          cordova prepare
          popd
      - name: Install dependencies
        run: npm install
      - name: Package platform:chromium
        run: npm run package:chromium
      - name: Package platform:firefox
        run: npm run package:firefox
      - name: Package platform:android
        run: npm run package:android
      - name: Set release version env var
        run: echo "RELEASE_VERSION=$(cat version.txt)" >> $GITHUB_ENV
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: ${{ github.event.inputs.beta_release == 'true' }}
          tag_name: v${{ env.RELEASE_VERSION }}
          body_path: CHANGELOG.md
          files: |
            dist/xbrowsersync_${{ env.RELEASE_VERSION }}_chromium.zip
            dist/xbrowsersync_${{ env.RELEASE_VERSION }}_firefox.zip
            dist/xbrowsersync_${{ env.RELEASE_VERSION }}_android.apk
            dist/xbrowsersync_${{ env.RELEASE_VERSION }}_android_unsigned.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
