name: Release
on:
  workflow_dispatch:
jobs:
  package:
    name: Package platforms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - run: npm run package:chromium
      - name: Set env vars
        run: |
          echo "1.6.0.0" > XBS_VERSION_1
          $(cat version.txt) > XBS_VERSION_2
      - name: Print env vars
        run: |
          echo "XBS_VERSION_1 = $XBS_VERSION_1"
          echo "XBS_VERSION_2 = $XBS_VERSION_2"
          echo "GITHUB_RUN_NUMBER = $GITHUB_RUN_NUMBER"
