name: Release
on:
  workflow_dispatch:
jobs:
  package:
    name: Package platforms
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm install
      - run: npm run package:chromium
      - name: Set release version env var
        run: echo "RELEASE_VERSION=$(cat release.txt)" >> $GITHUB_ENV
      - run: echo "RELEASE_VERSION = $RELEASE_VERSION"
      - name: Upload chromium package
        uses: actions/upload-artifact@v2
        with:
          name: chromium-package
          path: dist/xbrowsersync_${{ env.RELEASE_VERSION }}_chromium.zip
